run:front back
	./login/loginback.cgi&
	./viewtest/viewtestback.cgi&
	./studdetails/studdetailback.cgi&
	./checktest/checktestback.cgi&
	./signup/signupback.cgi&
	./logout/logoutback.cgi&
	./starttest/starttestback.cgi&
	./loadquestion/loadquestionback.cgi&
	./insertanswer/insertanswerback.cgi&
	./clearanswer/clearanswerback.cgi&
	./submittest/submittestback.cgi&	
	./checktestfile/checktestfileback.cgi&
	./uploadtestfile/uploadtestfileback.cgi&
	./viewreview/viewreviewback.cgi&
	./viewanswer/viewanswerback.cgi&

front:
	./compile.sh login/login
	./compile.sh viewtest/viewtest
	./compile.sh studdetails/studdetail
	./compile.sh checktest/checktest
	./compile.sh signup/signup
	./compile.sh logout/logout
	./compile.sh starttest/starttest
	./compile.sh loadquestion/loadquestion
	./compile.sh insertanswer/insertanswer
	./compile.sh clearanswer/clearanswer
	./compile.sh submittest/submittest	
	./compile.sh checktestfile/checktestfile
	./compile.sh uploadtestfile/uploadtestfile
	./compile.sh viewreview/viewreview
	./compile.sh viewanswer/viewanswer


back:
	./2comp.sh login/loginback
	./2comp.sh login/worker
	./2comp.sh viewtest/viewtestback
	./2comp.sh viewtest/worker
	./2comp.sh checktest/checktestback
	./2comp.sh studdetails/studdetailworker
	./2comp.sh studdetails/studdetailback
	./2comp.sh checktest/worker
	./2comp.sh signup/signupback
	./2comp.sh signup/worker
	./2comp.sh logout/logoutback
	./2comp.sh logout/worker
	./2comp.sh starttest/starttestback
	./2comp.sh starttest/worker
	./2comp.sh loadquestion/loadquestionback
	./2comp.sh loadquestion/worker
	./2comp.sh insertanswer/insertanswerback
	./2comp.sh insertanswer/insertanswerworker
	./2comp.sh clearanswer/clearanswerback
	./2comp.sh clearanswer/clearanswerworker
	./2comp.sh submittest/submittestback
	./2comp.sh submittest/worker
	./2comp.sh checktestfile/checktestfileback
	./2comp.sh checktestfile/worker
	./2comp.sh uploadtestfile/uploadtestfileback
	./2comp.sh uploadtestfile/worker
	./2comp.sh viewreview/viewreviewback
	./2comp.sh viewreview/viewreviewworker
	./2comp.sh viewanswer/viewanswerback
	./2comp.sh viewanswer/viewanswerworker

