run :	back kcgi
	./login/loginback.cgi&
	./testpage/testpageback.cgi&
	./displaydetails/displaydetailback.cgi&
	./viewreview/viewreviewback.cgi&
	./viewtests/viewtestsback.cgi&
	./viewanswer/viewanswerback.cgi&
	./createtest/createtestback.cgi&
	./insertall/insertallback.cgi&
	./selectstudents/selectstudentback.cgi&
	./insertquestion/insertqback.cgi&
	./proceed/proceedback.cgi&
	./submittest/submittestback.cgi&
	./checktestfile/checktestfileback.cgi&
	./uploadtestfile/uploadtestfileback.cgi&
	./logout/logoutback.cgi&

back:	
	./backcompile.sh ./login/worker
	./backcompile.sh ./login/loginback
	./backcompile.sh ./testpage/worker
	./backcompile.sh ./testpage/testpageback
	./backcompile.sh ./displaydetails/displaydetailworker
	./backcompile.sh ./displaydetails/displaydetailback
	./backcompile.sh ./viewreview/viewreviewworker
	./backcompile.sh ./viewreview/viewreviewback
	./backcompile.sh ./viewtests/viewtestsworker
	./backcompile.sh ./viewtests/viewtestsback
	./backcompile.sh ./viewanswer/viewanswerworker
	./backcompile.sh ./viewanswer/viewanswerback
	./backcompile.sh ./createtest/worker
	./backcompile.sh ./createtest/createtestback
	./backcompile.sh ./insertall/insertallw
	./backcompile.sh ./insertall/insertallback
	./backcompile.sh ./insertquestion/insertqback
	./backcompile.sh ./insertquestion/worker
	./backcompile.sh ./proceed/proceedback
	./backcompile.sh ./proceed/worker
	./backcompile.sh ./submittest/submittestback	
	./backcompile.sh ./submittest/submittestworker
	./backcompile.sh ./selectstudents/selectstudentback
	./backcompile.sh ./selectstudents/selectstudentw
	./backcompile.sh ./checktestfile/checktestfileback
	./backcompile.sh ./checktestfile/worker
	./backcompile.sh ./uploadtestfile/uploadtestfileback
	./backcompile.sh ./uploadtestfile/worker
	./backcompile.sh ./logout/logoutback
	./backcompile.sh ./logout/worker

kcgi:
	./kcgicompile.sh ./login/login
	./kcgicompile.sh ./testpage/testpage
	./kcgicompile.sh ./displaydetails/displaydetail
	./kcgicompile.sh ./viewreview/viewreview
	./kcgicompile.sh ./viewtests/viewtests
	./kcgicompile.sh ./viewanswer/viewanswer
	./kcgicompile.sh ./createtest/createtest
	./kcgicompile.sh ./insertall/insertall
	./kcgicompile.sh ./insertquestion/insertq
	./kcgicompile.sh ./proceed/proceed
	./kcgicompile.sh ./submittest/submittest
	./kcgicompile.sh ./selectstudents/selectstudents
	./kcgicompile.sh ./checktestfile/checktestfile
	./kcgicompile.sh ./uploadtestfile/uploadtestfile
	./kcgicompile.sh ./logout/logout

